---
- hosts: 192.168.99.131
  tasks:
    - name: Download the patch
      get_url:
        url: https://www.openssl.org/source/openssl-1.0.2h.tar.gz
        dest: /tmp

    - name: Extract the patch
      unarchive:
        src: /tmp/openssl-1.0.2h.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Install the patch
      command: 
        cmd: ./config && make && make test && make install
        chdir: /tmp/openssl-1.0.2h/
        creates: /usr/local/ssl/bin/openssl

    - name: Verify installation
      command: openssl version
      register: result

    - debug:
        var: result.stdout_lines
