---
- hosts: 192.168.99.131
  tasks:
    - name: Download the patch
      get_url:
        url: https://www.openssl.org/source/openssl-3.0.12.tar.gz
        dest: /tmp

    - name: Extract the patch
      unarchive:
        src: /tmp/openssl-3.0.12.tar.gz
        dest: /tmp
        remote_src: yes
        
    - name: 安装依赖-perl-ExtUtils-CBuilder
      yum:  
        name: perl-ExtUtils-CBuilder
        state: present
        use: '-y'

    - name: 安装依赖-perl-ExtUtils-MakeMaker
      yum:
        name: perl-ExtUtils-MakeMaker
        state: present
        use: '-y'

    - name: Configure and build OpenSSL
      command:
        cmd: ./config --prefix=/usr/lib/openssl/openssl
        chdir: /tmp/openssl-3.0.12/
      
    - name: Build OpenSSL
      command:
        cmd: make
        chdir: /tmp/openssl-3.0.12/

    # - name: Test OpenSSL  
    #   command:
    #     cmd: make test
    #     chdir: /tmp/openssl-3.0.12/
      
    - name: Install OpenSSL  
      command:
        cmd: make install
        chdir: /tmp/openssl-3.0.12/

    - name: sudo ldconfig
      command:
        cmd: sudo ldconfig

    - name: 修改环境变量 
      command:
        cmd: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/openssl/openssl/lib64
     
    - name: Verify installation
      command: openssl version
      register: result

    - debug:
        var: result.stdout_lines
